server:
  port: 8081
  servlet:
    context-path: "/api/v1/"


spring:
  liquibase:
    enabled: true
    default-schema: reminder_schema

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:55000/reminderdb
    username: postgres
    password: postgrespw

  jpa:
    show-sql: true
    generate-ddl: false
    open-in-view: true


jwt:
  secret: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
  jwt-lifetime: 15m